# Generated by Django 3.0.4 on 2020-03-19 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=25, verbose_name='Stream Location')),
                ('name', models.CharField(max_length=25, verbose_name='Device Id')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25, verbose_name='Email')),
                ('password', models.CharField(max_length=25, verbose_name='Password')),
                ('device_owned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeHomeDatabase.Devices')),
            ],
        ),
    ]
