# Generated by Django 3.0.4 on 2020-04-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeHomeDatabase', '0004_auto_20200328_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='temp',
            field=models.CharField(default='NONE', max_length=60, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Device Name'),
        ),
    ]
